import { Octokit } from "@octokit/rest";

/**
 * Build an authenticated Octokit instance from the GH_PAT or GITHUB_TOKEN
 * environment variables.
 *
 * Uses `.trim() ||` instead of `??` because GitHub Actions may expose unset
 * secrets as empty strings, making nullish coalescing unreliable.
 */
export function buildOctokit(): Octokit {
  const token =
    process.env.GH_PAT?.trim() ||
    process.env.GITHUB_TOKEN?.trim();

  if (!token) {
    throw new Error(
      "No GitHub token found. Set GH_PAT (for cross-repo access) or GITHUB_TOKEN."
    );
  }
  return new Octokit({ auth: token });
}

/**
 * Parse a "owner/repo" string into its constituent parts.
 * Throws when the format is invalid.
 */
export function parseRepo(ownerRepo: string): { owner: string; repo: string } {
  const parts = ownerRepo.split("/");
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new Error(
      `Invalid repository format "${ownerRepo}". Expected "owner/repo".`
    );
  }
  return { owner: parts[0], repo: parts[1] };
}

/**
 * Return the base branch of a repository (defaults to "main" when unset).
 */
export async function defaultBranch(
  octokit: Octokit,
  owner: string,
  repo: string
): Promise<string> {
  const { data } = await octokit.repos.get({ owner, repo });
  return data.default_branch ?? "main";
}

/**
 * Create a dedicated healing branch (`dot/heal/<runId>`) branching from the
 * tip of the repository's default branch.  Returns the new branch name.
 */
export async function createHealingBranch(
  octokit: Octokit,
  owner: string,
  repo: string,
  runId: number
): Promise<string> {
  const base = await defaultBranch(octokit, owner, repo);

  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${base}`,
  });
  const sha = ref.object.sha;

  const branchName = `dot/heal/${runId}`;
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha,
  });

  return branchName;
}

/**
 * Open (or locate an existing) pull request from `healingBranch` into the
 * repository's default branch.  Returns the PR URL.
 */
export async function openHealingPr(
  octokit: Octokit,
  owner: string,
  repo: string,
  healingBranch: string,
  runId: number
): Promise<string> {
  const base = await defaultBranch(octokit, owner, repo);

  // Check whether a PR already exists for this branch.
  const existing = await octokit.pulls.list({
    owner,
    repo,
    state: "open",
    head: `${owner}:${healingBranch}`,
  });

  if (existing.data.length > 0) {
    return existing.data[0].html_url;
  }

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: `fix: DOT automated healing for run #${runId}`,
    head: healingBranch,
    base,
    body:
      `This pull request was automatically generated by **DOT** to address ` +
      `failures detected in workflow run [#${runId}](https://github.com/${owner}/${repo}/actions/runs/${runId}).\n\n` +
      `Please review and merge if the proposed changes look correct.`,
  });

  return pr.html_url;
}
