name: QueenFi703/Github bootstrap app
description: A collection of actions for building Gradle projects, as well as generating a dependency graph via Dependency Submission.

runs:
  using: "composite"
  steps:
  - run: |
      echo "::error::The path 'QueenFi703/actions' is not a valid action. Please use 'QueenFi703/actions/setup-gradle' or 'QueenFi703/actions/dependency-submission'."
      exit 1
    shell: bash

branding:
  icon: 'box'
  color: 'gray-dark'
