// .ai/dredge/registry/gradle/fix-wrapper.ts
// Patch: regenerate or repair the Gradle wrapper when it is missing or broken.

import * as fs from 'fs'
import * as path from 'path'
import type { PatchPlugin, PatchContext, PatchResult } from '../../types.js'

const WRAPPER_JAR = path.join('gradle', 'wrapper', 'gradle-wrapper.jar')
const WRAPPER_PROPERTIES = path.join('gradle', 'wrapper', 'gradle-wrapper.properties')
const GRADLEW = 'gradlew'

/**
 * Signal shape expected by this patch.
 */
interface WrapperSignal {
    /** True when any of the required wrapper files are absent. */
    missingFiles?: string[]
    /** True when gradle-wrapper.properties references an unsupported distribution. */
    invalidDistributionUrl?: boolean
}

function wrapperNeedsRepair(signal: WrapperSignal): boolean {
    const missing = signal.missingFiles ?? []
    return missing.length > 0 || signal.invalidDistributionUrl === true
}

/** Minimal default wrapper properties that point to a recent Gradle release. */
const DEFAULT_WRAPPER_PROPERTIES = [
    'distributionBase=GRADLE_USER_HOME',
    'distributionPath=wrapper/dists',
    'distributionUrl=https\\://services.gradle.org/distributions/gradle-8.14-bin.zip',
    'networkTimeout=10000',
    'validateDistributionUrl=true',
    'zipStoreBase=GRADLE_USER_HOME',
    'zipStorePath=wrapper/dists',
].join('\n')

/** Minimal gradlew shell script that properly delegates to the Gradle wrapper. */
const DEFAULT_GRADLEW = `#!/bin/sh
# Minimal gradlew stub generated by DREDGE fix-wrapper patch.
# Run "gradle wrapper --gradle-version 8.14" to replace this with a full wrapper.
set -e
APP_HOME="$(cd "$(dirname "$0")" && pwd)"
JAVA_OPTS=""
exec java \${JAVA_OPTS} -classpath "\${APP_HOME}/gradle/wrapper/gradle-wrapper.jar" \\
    org.gradle.wrapper.GradleWrapperMain "$@"
`

export const fixWrapper: PatchPlugin = {
    id: 'gradle/fix-wrapper',
    domain: 'gradle_config',

    match(signal: unknown): boolean {
        return wrapperNeedsRepair(signal as WrapperSignal)
    },

    async apply(context: PatchContext): Promise<PatchResult> {
        const root = context.repoRoot
        const changes: string[] = []

        const wrapperDir = path.resolve(root, 'gradle', 'wrapper')
        if (!fs.existsSync(wrapperDir)) {
            fs.mkdirSync(wrapperDir, { recursive: true })
        }

        const propertiesPath = path.resolve(root, WRAPPER_PROPERTIES)
        if (!fs.existsSync(propertiesPath)) {
            fs.writeFileSync(propertiesPath, DEFAULT_WRAPPER_PROPERTIES + '\n', 'utf8')
            changes.push(WRAPPER_PROPERTIES)
        }

        const gradlewPath = path.resolve(root, GRADLEW)
        if (!fs.existsSync(gradlewPath)) {
            fs.writeFileSync(gradlewPath, DEFAULT_GRADLEW, 'utf8')
            fs.chmodSync(gradlewPath, 0o755)
            changes.push(GRADLEW)
        }

        // If the wrapper JAR is explicitly listed as missing we note it — the
        // actual binary can only be regenerated by running `gradle wrapper`.
        const jarPath = path.resolve(root, WRAPPER_JAR)
        if (!fs.existsSync(jarPath)) {
            changes.push(`${WRAPPER_JAR} (requires: gradle wrapper --gradle-version 8.14)`)
        }

        const changed = changes.length > 0

        return {
            changed,
            message: changed
                ? `Repaired Gradle wrapper: ${changes.join(', ')}`
                : 'Gradle wrapper is already present and valid',
        }
    },
}
