name: Validate GitHub Action Typings

on:
  push:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - 'dist/**'

  pull_request:

permissions:
  contents: read

jobs:
  validate-typings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # 🧠 Optional but stabilizes environments long-term
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate GitHub Actions typings
        uses: typesafegithub/github-actions-typing@9ddf35b71a482be7d8922b28e8d00df16b77e315
        with:
          ignored-action-files: |
            .github/actions/build-dist/action.yml
            .github/actions/init-integ-test/action.yml
            action.yml
